
FROM gcc:12.2.0 as builder


RUN apt-get update && \
    apt-get install -y \
    libpq-dev \
    cmake \
    postgresql-client\
    curl 

WORKDIR /app

COPY backend/ ./

RUN make

FROM debian:bullseye-slim

RUN apt-get update && \
apt-get install -y libpq5 curl && \ 
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/airline_server /usr/local/bin/

WORKDIR /app

EXPOSE 8080

CMD ["airline_server"]

