# Базовий образ Nginx
FROM nginx:alpine

# Видаляємо дефолтну конфігурацію Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копіюємо нашу конфігурацію Nginx
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# Копіюємо файли фронтенду
COPY frontend/ /usr/share/nginx/html/

# Відкриваємо порт 80
EXPOSE 80

# Запускаємо Nginx
CMD ["nginx", "-g", "daemon off;"]




